name: Set Matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: 'Matrix of changed projects'
        value: ${{ jobs.set-matrix.outputs.matrix }}

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed projects
        id: set-matrix
        run: |
          # Find changed directories under projects/ for PRs or pushes
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            git fetch origin ${{ github.base_ref }}
            CHANGED=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep '^projects/' | awk -F'/' '{print $2}' | sort -u)
          else
            CHANGED=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '^projects/' | awk -F'/' '{print $2}' | sort -u)
          fi
          # Fallback: if nothing changed, run all
          if [ -z "$CHANGED" ]; then
            CHANGED=$(ls projects)
          fi
          # Exclude example-project
          CHANGED=$(echo "$CHANGED" | grep -v '^example-project$')
          # Build JSON array
          MATRIX=$(printf '%s\n' $CHANGED | jq -R . | jq -s .)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
