name: Terraform CD

# Prevent running CD jobs in the same branch
# If the user wants to run a new one, they must manually cancel the existing jobs
concurrency:
  group: terraform-cd-${{ github.ref }}
  cancel-in-progress: false
on:
  workflow_dispatch:
    inputs: 
      project-name:
        description: "Project name if you want to run only for a specific project. If not provided, all projects will be run."
        required: true
        type: string
jobs:
  set-matrix:
    uses: one-project-one-month/common-workflows/.github/workflows/common-set-matrix.yml@main

  terraform-apply:
    needs: set-matrix
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        project: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    uses: one-project-one-month/common-workflows/.github/workflows/common-terraform-plan.yml@main
    with:
      project: ${{ matrix.project }}

      s3_bucket: ${{ vars.TF_STATE_S3_BUCKET }}
      tf_cli_config_file: "../../../modules/terraformrc.tfrc"
      tf_provider_template: "../../_templates/providers-template
    
    secrets: 
      s3_access_key: ${{ secrets.TF_STATE_S3_ACCESS_KEY_ID }}
      s3_secret_key: ${{ secrets.TF_STATE_S3_SECRET_ACCESS_KEY }}
      github_checkout_token: ${{ secrets.GH_TOKEN_SVC_PUBLISH }}