name: Terraform CI

concurrency:
  group: terraform-ci-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch: 
  pull_request_review: 
  push:
    branches:
      - main
    paths:
      - 'projects/**'
      - '!projects/example-project/**'
  pull_request:
    paths:
      - 'projects/**'
      - '!projects/example-project/**'

jobs:
  set-matrix:
    uses: one-project-one-month/common-workflows/.github/workflows/common-set-matrix.yml@main

  terraform-ci:
    needs: set-matrix
    strategy:
      max-parallel: 5
      matrix:
        project: ${{ fromJson(needs.set-matrix.outputs.project-name) }}
    
    uses: one-project-one-month/common-workflows/.github/workflows/common-terraform-plan.yml@main
    with:
      project: ${{ matrix.project }}
      s3_bucket: ${{ vars.TF_STATE_S3_BUCKET }}
      tf_provider_template: "../../_templates/providers-template"

    secrets: 
      s3_access_key: ${{ secrets.TF_STATE_S3_ACCESS_KEY_ID }}
      s3_secret_key: ${{ secrets.TF_STATE_S3_SECRET_ACCESS_KEY }}
      github_checkout_token: ${{ secrets.GH_TOKEN_SVC_PUBLISH }}